buildscript {
    repositories {
        jcenter()
        maven { url = "https://files.minecraftforge.net/maven" }
        mavenCentral()
    }
    dependencies
            {
                classpath 'net.minecraftforge.gradle:ForgeGradle:2.3-SNAPSHOT'
            }
}

apply plugin: 'net.minecraftforge.gradle.forge'
// Only edit below this line, the above code adds and enables the necessary things for Forge to be setup.
apply plugin: 'eclipse'
apply plugin: 'maven-publish'

version = '1.0.1-1.12.2'
group = 'com.devmaster.random_dungeon_spawners'
archivesBaseName = 'random_dungeon_spawners'

sourceCompatibility = targetCompatibility = compileJava.sourceCompatibility = compileJava.targetCompatibility = '1.8' // Need this here so eclipse task generates correctly.

minecraft {

    version = "${minecraft_version}-${forge_version}"
    mappings = minecraft_mappings
    makeObfSourceJar = false
    runDir = "run"
}

dependencies {

}

jar {
    manifest {
        attributes([
            "Specification-Title": "RandomDungeonSpawners",
            "Specification-Vendor": "randomdungeonspawnerssareus",
            "Specification-Version": "1", // We are version 1 of ourselves
            "Implementation-Title": project.name,
            "Implementation-Version": "${version}",
            "Implementation-Vendor" :"randomdungeonspawnerssareus",
            "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

jar.finalizedBy('reobfJar')

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file:///${project.projectDir}/mcmodsrepo"
        }
    }
}